MyBlogNight.PresentationLayer/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;
using MyBlogNight.BusinessLayer.Abstract;

namespace MyBlogNight.PresentationLayer.Controllers
{
    public class DefaultController : Controller
    {

        public IActionResult Index()
        {
           
            return View();
        }
    }
}

MyBlogNight.PresentationLayer/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;
using MyBlogNight.BusinessLayer.Abstract;
using X.PagedList.Extensions;
using X.PagedList;
using MyBlogNight.EntityLayer.Concrete;
using Microsoft.AspNetCore.Identity;

namespace MyBlogNight.PresentationLayer.Controllers
{
    public class HomePageController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly ICommentService _commentService;
        private readonly INewsLetterService _newsletterService;
        private readonly UserManager<AppUser> _userManager;

        public HomePageController(IArticleService articleService, UserManager<AppUser> userManager, ICommentService commentService, INewsLetterService newsletterService)
        {
            _articleService = articleService;
            _userManager = userManager;
            _commentService = commentService;
            _newsletterService = newsletterService;
        }

        public IActionResult Index(int page = 1)
        {

            var values = _articleService.TArticleListWithCategoryAndAppUser().ToPagedList(page, 3);
            return View(values);
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(Comment comment)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            comment.AppUserId = user.Id;
            comment.CreatedDate = DateTime.Now;
            comment.Status = true;

            _commentService.TInsert(comment);

            return Redirect($"/Article/ArticleDetail/{comment.ArticleId}");
        }

        [HttpPost]
        public IActionResult AddNewsLatter(NewsLetter newsLetter)
        {
            _newsletterService.TInsert(newsLetter);
            return RedirectToAction("Index");
        }
    }
}

MyBlogNight.PresentationLayer/Views/Shared/Components/_HomePageNewsLetterComponentPartial/Default.cshtml
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<div class="newsletter-widget text-center align-self-center">
    <h3>Bugün Abone Olun!</h3>
    <p>
        Haftalık Bültenimize abone olun ve güncellemeleri e-posta yoluyla alın.
    </p>
    <form class="form-inline" id="newsletterForm" method="post" asp-action="AddNewsLatter" asp-controller="HomePage">
        <input type="email" name="Email" placeholder="Email Adresinizi Giriniz..." required class="form-control" />
        <button type="button" class="btn btn-default btn-block" id="btn1">Üye Ol</button>
    </form>
</div><!-- end newsletter -->

<script>
    document.getElementById('btn1').addEventListener('click', function () {
        swal({
            title: "Başarıyla Abone Oldunuz",
            text: "Harika! Haftalık bültenimiz artık e-posta kutunuzda olacak. İlginç içerikleri kaçırmayın!",
            icon: "success",
            button: "Tamam",
        });

        // 5 saniye sonra formu gönder ve yönlendir
        setTimeout(function () {
            document.getElementById('newsletterForm').submit(); // Form gönderme
        }, 5000); // 5000ms = 5 saniye
    });
</script>